# Generated by Django 3.2.9 on 2022-08-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.CharField(max_length=5)),
                ('time_finish', models.CharField(max_length=5)),
                ('day_finish', models.CharField(max_length=8)),
                ('day_start', models.CharField(max_length=8)),
                ('number_bus', models.CharField(max_length=10)),
                ('cost', models.IntegerField(null=True)),
                ('trevel_time', models.CharField(max_length=10, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='station.routes')),
            ],
        ),
    ]
