# Generated by Django 3.2.9 on 2022-08-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='route',
            new_name='routes',
        ),
    ]
